name: evently

services:
  database:
    image: postgres:16.3-alpine3.20
    container_name: Database
    environment:
      - POSTGRES_DB=evently
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 1001:5432

  redis:
    image: redis:alpine3.20
    container_name: Redis
    restart: always
    ports:
      - 1002:6379

  seq:
    image: datalust/seq:2024.3
    container_name: Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 1101:80
        
  identity:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      # - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 1201:8080