name: evently

services:
  api:
    image: evently.api
    container_name: Api
    build:
      context: .
      dockerfile: src/API/Evently.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
  
  database:
    image: postgres:16.3-alpine3.20
    container_name: database
    environment:
      - POSTGRES_DB=evently
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 1001:5432

  redis:
    image: redis:alpine3.20
    container_name: redis
    restart: always
    ports:
      - 1002:6379

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 1101:80